POST http://localhost:8080/register

{
    "username": "exampleUser",
    "user_password": "examplePassword123!",
    "email": "example@example.com",
    "first_name": "John",
    "last_name": "Doe",
    "user_bio": "I am an example user.",
    "birthday": "2000-01-01",
    "profile_picture_url": "http://example.com/profile.jpg",
    "notifications_enabled": true,
    "latitude": 40.7128,
    "longitude": -74.0060,
    "session_token": "exampleToken"
}
